version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - zodiacnet
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/zodiacbot

  frontend:
    build:
      context: ./Frontend
    ports:
      - "5713:5713"
    restart: unless-stopped
    networks:
      - zodiacnet

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - zodiacnet

networks:
  zodiacnet:
    driver: bridge

volumes:
  mongodb_data:
